### PR TITLE
linsolve: update for change in mat.DiagDense API

### LINKED ISSUE #20: linsolve: test fails with undefined: mat.NewDiagonal
running `go test` in travis fails (locally too) with:
```
$> go test ./...
# gonum.org/v1/exp/linsolve [gonum.org/v1/exp/linsolve.test]
linsolve/linsolve_test.go:154:7: undefined: mat.NewDiagonal
```

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

Fixes #20.

### CODE REVIEW

File: linsolve/linsolve_test.go [hunk 1]
```diff
@@ -366,7 +366,7 @@ func newGreenbaum73(nx, ny int, rnd *rand.Rand) testCase {
 		negOne, negOne, // - ∂_x ∂_x u - ∂_y ∂_y u
 		func(x, _ float64) float64 { return 40 * x }, // 40 * x * ∂_x u
 		func(_, y float64) float64 { return 40 * y }, // 40 * y * ∂_y u
-		constant(-100),                               // -100 * u
+		constant(-100), // -100 * u
```
Comment (kortschak) [inline linsolve/linsolve_test.go]: This change in due, I think, to a change in gofmt tuning.

Comment (vladimir-ch) [reply linsolve/linsolve_test.go]: I think it depends on which formatting program is used. I've seen it change between goimports or goreturns, IIRC.

Comment (kortschak) [reply linsolve/linsolve_test.go]: Yeah, maybe, but there was a recent change to the line length comparison calculations recently.
